# Generated by Django 5.2.5 on 2025-09-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_persona_options_alter_tarea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='id',
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(db_column='T001Activo', default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(db_column='T001Apellido', default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(db_column='T001IdPersona', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_tarea',
            field=models.AutoField(db_column='T002IdTarea', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(db_column='T001Documento', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(db_column='T001Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(db_column='T001Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(db_column='T002Descripcion'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(db_column='T002Fechalimite'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='persona',
            field=models.ForeignKey(db_column='T002PersonaId', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api_app.persona'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(db_column='T002Titulo', max_length=200),
        ),
        migrations.AlterModelTable(
            name='persona',
            table='T001Persona',
        ),
        migrations.AlterModelTable(
            name='tarea',
            table='T002Tarea',
        ),
    ]
